### ISSUE TITLE
Populate MySQL database

### ISSUE THREAD

**Issue by EddyTheDove** [JimLiu/express-seed#4]
Hi, 
Sorry I am totally new to Nodejs environment from PHP, like just starting this week. My question is, how do you run the db.sql schema to the actual mysql database? Like from PHP (Laravel), we do `php artisan migrate`.
Even more, how do I run sql queries? Is there like an ORM. I think now I am asking for too much.

**Comment by JimLiu** [comment]
Hi 

You need to create a new mysql database, and execute the `db.sql` on the database.

The [`node-mysql`](https://github.com/mysqljs/mysql) module does the ORM work, so the query result is javascript Object.

BTW: this project is out of date, just FYI.

Thanks

**Comment by EddyTheDove** [comment]
Hi JimLiu 
Thanks for replying. Which project could you recommend me to use, please?

**Comment by JimLiu** [comment]
@EddyTheDove 
What kind of project do you want to build?

**Comment by EddyTheDove** [comment]
I want to build a node project that will work with jade. That's what I want to learn for now. Thank you for your time @JimLiu

**Comment by JimLiu** [comment]
@EddyTheDove 
I think you can use this, it's simple and easy to extend.

The others:
https://github.com/TryGhost/Ghost
https://github.com/ParsePlatform/parse-server
